#!/bin/bash

kpackage=linux
kmodules=$(pacman -Ql ${kpackage} | grep /usr/lib/modules | grep vmlinuz | cut -d '/' -f 5)

dracut -f -H --no-hostonly-cmdline /boot/initramfs-dracut-${kpackage}.img $kmodules
dracut -f -N /boot/initramfs-dracut-${kpackage}-fallback.img $kmodules